--ALTER TABLE CHATTING     DROP CONSTRAINT CHATTING_FOREIGN_STUDENTNO;
--ALTER TABLE CHATTING     DROP CONSTRAINT CHATTING_FOREIGN_ROOONO;
--ALTER TABLE PARTICIPANTS DROP CONSTRAINT PARTICIPANTS_FOREIGN_ROOMNO;
--ALTER TABLE PARTICIPANTS DROP CONSTRAINT PARTICIPANTS_FOREIGN_STUDENTNO;
--
--ALTER TABLE CHATTING     DROP CONSTRAINT CHATTING_PK;
--ALTER TABLE MEMBER       DROP CONSTRAINT MEMBER_PK;
--ALTER TABLE NOTICE       DROP CONSTRAINT NOTICE_PK;
--ALTER TABLE PARTICIPANTS DROP CONSTRAINT PARTICIPANTS_PK;
--
--DROP TABLE MEMBER;
--DROP TABLE CHATTING_ROOM;
--DROP TABLE CHATTING;
--DROP TABLE PARTICIPANTS;
--DROP TABLE NOTICE;



CREATE TABLE MEMBER(
 studentNo NUMBER NOT NULL,
 id VARCHAR2(100) NOT NULL,
 password VARCHAR2(1000) NOT NULL,
 name VARCHAR2(10) NOT NULL,
 grade NUMBER NOT NULL,
 subject VARCHAR2(100) NOT NULL,
 ip VARCHAR2(100) NOT NULL,
 job VARCHAR2(100) );
CREATE UNIQUE INDEX MEMBER_PK ON MEMBER (studentNo);
ALTER TABLE MEMBER ADD CONSTRAINT MEMBER_PK PRIMARY KEY (STUDENTNO) USING INDEX;
 
 CREATE TABLE CHATTING_ROOM(
roomNo NUMBER NOT NULL,
roomNm VARCHAR2(1000) NOT NULL);
CREATE UNIQUE INDEX CHATTING_ROOM_PK ON CHATTING_ROOM(roomNo);
ALTER TABLE CHATTING_ROOM ADD CONSTRAINT CHATTING_ROOM_PK PRIMARY KEY(roomNo) USING INDEX;

 CREATE TABLE chatting( 
 chatindex NUMBER NOT NULL,
 studentNo NUMBER NOT NULL,
 content VARCHAR2(4000) NOT NULL,
 roomNo NUMBER NOT NULL
 );
CREATE UNIQUE INDEX CHATTING_PK ON CHATTING(chatindex);
ALTER TABLE CHATTING ADD CONSTRAINT CHATTING_PK PRIMARY KEY (chatindex) USING INDEX;
ALTER TABLE CHATTING ADD CONSTRAINT CHATTING_FOREIGN_STUDENTNO FOREIGN KEY(studentNo) REFERENCES MEMBER(studentNo);
ALTER TABLE CHATTING ADD CONSTRAINT CHATTING_FOREIGN_ROOONO FOREIGN KEY(roomNo) REFERENCES CHATTING_ROOM(roomNo);

CREATE TABLE PARTICIPANTS(
partIndex NUMBER NOT NULL,
studentNo NUMBER NOT NULL,
roomNo NUMBER NOT NULL);
CREATE UNIQUE INDEX PARTICIPANTS_PK ON PARTICIPANTS(partIndex);
ALTER TABLE PARTICIPANTS ADD CONSTRAINT PARTICIPANTS_PK PRIMARY KEY(partIndex) USING INDEX;
ALTER TABLE PARTICIPANTS ADD CONSTRAINT PARTICIPANTS_FOREIGN_STUDENTNO FOREIGN KEY(studentNo) REFERENCES MEMBER(studentNo);
ALTER TABLE PARTICIPANTS ADD CONSTRAINT PARTICIPANTS_FOREIGN_ROOMNO FOREIGN KEY(roomNo) REFERENCES CHATTING_ROOM(roomNo);

 CREATE TABLE notice( 
 noticeIndex NUMBER NOT NULL,
 noticeTitle VARCHAR2(1000) NOT NULL,
 noticeContent VARCHAR2(4000) NOT NULL);
 CREATE UNIQUE INDEX NOTICE_PK ON NOTICE(noticeIndex);
 ALTER TABLE notice ADD CONSTRAINT NOTICE_PK PRIMARY KEY (noticeIndex) USING INDEX;
 
 CREATE SEQUENCE CHATTING_ROOM_SQ START WITH 1;
 CREATE SEQUENCE CHATTING_SQ START WITH 1;
 CREATE SEQUENCE PARTICIPANTS_SQ START WITH 1;
 CREATE SEQUENCE NOTICE_SQ START WITH 1;