INSERT INTO MEMBER(STUDENTNO, ID, PASSWORD, NAME, GRADE, SUBJECT, IP, JOB)
VALUES (201914132, 'SHUAI1593', 'RLAEHDDNR12', '김솔', 3, '정통', '192.168.35.88', '학생');

DESC MEMBER;

SELECT * FROM MEMBER;

INSERT INTO CHATTING_ROOM (ROOMNO, ROOMNM)
VALUES (CHATTING_ROOM_SQ.NEXTVAL, 'RAND');

SELECT * FROM CHATTING_ROOM;




INSERT INTO MEMBER(STUDENTNO, ID, PASSWORD, NAME, GRADE, SUBJECT, IP, JOB)
VALUES (201433005, 'KDW0725', 'RLAEHDDNR12', '김아무', 4, '정통', '192.168.35.88', 'DBA');

INSERT INTO MEMBER(STUDENTNO, ID, PASSWORD, NAME, GRADE, SUBJECT, IP, JOB)
VALUES (201433028, 'yooja8745', 'RLAEHDDNR12', '유자', 4, '정통', '192.168.35.88', '잡부');




SELECT STUDENTNO, ID, NAME, GRADE, SUBJECT, JOB FROM MEMBER WHERE ID = 'SHUAI1593' AND PASSWORD = 'RLAEHDDNR12';

commit;

SELECT * FROM PARTICIPANTS ;

SELECT ROOMNO FROM (SELECT LISTAGG(STUDENTNO, ',') WITHIN GROUP(ORDER BY ROOMNO, studentno) AS CLIENT, ROOMNO FROM PARTICIPANTS GROUP BY ROOMNO) WHERE CLIENT = '201433005,201914132'



;

SELECT LISTAGG(STUDENTNO, ',') WITHIN GROUP(ORDER BY ROOMNO, studentno) AS CLIENT, ROOMNO FROM PARTICIPANTS GROUP BY ROOMNO
;

SELECT CLIENT, ROOMNO FROM (SELECT LISTAGG(STUDENTNO, ',') WITHIN GROUP(ORDER BY ROOMNO, STUDENTNO) AS CLIENT, ROOMNO FROM PARTICIPANTS GROUP BY ROOMNO) WHERE CLIENT = '201433005'||',' ||'201914132';



;
select CONCAT('201433005','201914132') from dual;

SELECT * FROM CHATTING;